// Code generated by "stringer -type=ErrorType -linecomment -output error_string.gen.go"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorTypeValidationFailed-1]
	_ = x[ErrorTypeRegistAdminValidationFailed-2]
	_ = x[ErrorTypeAdminEmailValidationFailed-3]
	_ = x[ErrorTypeAdminLoginValidationFailed-4]
	_ = x[ErrorTypeRegistItemAlreadyRegistered-5]
	_ = x[ErrorTypePasswordOrEmailValidationFailed-6]
	_ = x[ErrorTypeRegistMemberValidationFailed-7]
	_ = x[ErrorTypeAuthenticationFailed-8]
	_ = x[ErrorTypeNotFound-9]
	_ = x[ErrorTypeInternalError-10]
}

const _ErrorType_name = "validation_failedregist admin validation_failedErrorTypeAdminEmailValidationFailedErrorTypeAdminLoginValidationFailedregist item validation_failedErrorTypePasswordOrEmailValidationFailedErrorTypeRegistMemberValidationFailedauthentication_faildnot_foundinternal_error"

var _ErrorType_index = [...]uint16{0, 17, 47, 82, 117, 146, 186, 223, 243, 252, 266}

func (i ErrorType) String() string {
	i -= 1
	if i < 0 || i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
