openapi: 3.0.2
info:
  title: vtm
  description: vtm勤怠管理
  version: 1.0.0
  termsOfService: 'https://code0716.com/'
  contact:
    name: Code0716
servers:
  - url: 'https://example.com/api/v1'
paths:
  /login:
    post:
      operationId: Login
      summary: login
      description: login
      tags:
        - common
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mail_address:
                  type: string
                  description: name
                password:
                  type: string
                  description: password
              required:
                - mail_address
                - password
      responses:
        '200':
          description: loginが成功した場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/AuthenticationResponse'
        default:
          $ref: '#/components/responses/InternalServerError'
  /user/list:
    get:
      security:
        - security: []
      operationId: getUserList
      summary: user情報取得
      description: user一覧を取得する。
      tags:
        - user
      responses:
        '200':
          description: userの取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'
        default:
          $ref: '#/components/responses/InternalServerError'
  /user/{uuid}:
    get:
      security:
        - security: []
      operationId: getUser
      summary: user情報取得
      description: userを取得する。
      tags:
        - user
      parameters:
        - name: uuid
          in: path
          required: true
          description: user uuid
          schema:
            type: string
      responses:
        '200':
          description: userの取得
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/User'
        default:
          $ref: '#/components/responses/InternalServerError'
    put:
      security:
        - security: []
      operationId: updateUser
      summary: user情報更新
      description: userを更新する。
      tags:
        - user
      parameters:
        - name: uuid
          in: path
          required: true
          description: user uuid
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: name
                phone_number:
                  type: string
                  description: phone number
                status:
                  type: string
                  description: status
                hourly_price:
                  type: integer
                  format: int64
                  description: hourly price
              required:
                - phone_number
                - name
                - status
      responses:
        '201':
          description: userの更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                  total:
                    type: integer
        default:
          $ref: '#/components/responses/InternalServerError'
  /timestamp/{uuid}:
    post:
      security:
        - security: []
      operationId: Timestamp
      summary: 打刻
      description: 打刻する。
      tags:
        - user
      parameters:
        - name: uuid
          in: path
          required: true
          description: user uuid
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: user id
                status:
                  type: string
                  enum:
                    - BEGIN_WORK
                    - BEGIN_REST
                    - END_WORK
                    - END_REST
              required:
                - user_id
                - status
      responses:
        '200':
          description: 打刻成功時
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attendance'
        default:
          $ref: '#/components/responses/InternalServerError'
tags:
  - name: Users
    description: users api
components:
  securitySchemes:
    security:
      type: apiKey
      in: header
      name: authorization
  parameters:
    LimitParam:
      description: limit params
      in: query
      name: limit
      schema:
        type: integer
        default: 50
      required: false
    OffsetParam:
      in: query
      name: offset
      description: offset param
      schema:
        type: integer
        default: 0
      required: false
    StatusParam:
      in: query
      name: status
      description: status param
      schema:
        type: string
      required: false
  schemas:
    User:
      description: User
      type: object
      properties:
        id:
          description: ID
          type: integer
          format: int64
        user_id:
          description: user_id
          type: string
        name:
          description: name
          type: string
        mail_address:
          description: mail address
          type: string
        phone_number:
          description: phone
          type: string
        password:
          description: password
          type: string
        status:
          description: status
          type: string
          enum:
            - init
            - active
            - other
        permission:
          description: user permission
          type: string
          enum:
            - admin
            - manager
            - accountant
            - common
        employment_status:
          description: 給与形態
          type: string
          enum:
            - annual
            - monthly
            - hourly
            - day
            - other
        unit_price:
          description: 月給/単価
          type: integer
          format: int64
        department_id:
          description: 所属部署/所属店舗のID(UUID)
          type: string
        created_at:
          description: 登録日
          type: string
          format: date-time
        updated_at:
          description: 更新日
          type: string
          format: date-time
        deleted_at:
          description: 削除日
          type: string
          format: date-time
      required:
        - id
        - user_id
        - name
        - phone_number
        - status
        - created_at
        - updated_at
    Attendance:
      description: 打刻情報
      type: object
      properties:
        id:
          description: ID
          type: integer
          format: int64
        date:
          description: 打刻時間
          type: string
          format: date-time
        user_id:
          description: menber_id uuid
          type: string
        status:
          description: status
          type: string
        deleted_at:
          description: 削除日
          type: string
          format: date-time
    Error:
      description: エラー
      type: object
      properties:
        code:
          type: string
          description: エラーコード
        message:
          type: string
          description: エラー内容
        status:
          description: status
          type: integer
          format: int64
      required:
        - code
        - message
    ErrorResponse:
      description: エラーレスポンス
      type: object
      properties:
        errors:
          type: array
          description: エラー一覧
          items:
            $ref: '#/components/schemas/Error'
      required:
        - errors
    CommonSuccessResponse:
      description: 更新、登録、削除など成功した際の汎用レスポンス
      type: object
      properties:
        message:
          type: string
          description: message
      required:
        - message
    AuthenticationResponse:
      description: ログイン時のレスポンス
      type: object
      properties:
        message:
          type: string
          description: message
        token:
          type: string
          description: token
      required:
        - message
        - updated_at
    UsersResponse:
     type: array
     description: User一覧のレスポンス
     items: 
      $ref: '#/components/schemas/User'

      # properties:
      #   errors:
      #     type: array
      #     description: エラー一覧
      #     items:
  responses:
    InternalServerError:
      description: 予期していないエラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
# security:
#   - security: []
