name: vtm Test

on: [push]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.13
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: vtm_db
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ADMIN_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_PORT: 3306
          MYSQL_DIALECT: 'mysql'
          MYSQL_CHARSET: 'utf8mb4'
          MYSQL_TIMEZONE: Asia/Tokyo
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: setup
        run: |
          make clean
          make install-build-tools
          make deps
      - name: run test
        run: go test -race -v ./...
        env:
          MYSQL_HOST: $MYSQL_HOST
          MYSQL_DBNAME: $MYSQL_DBNAME
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ADMIN_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_PORT: $MYSQL_PORT
          MYSQL_DIALECT: $MYSQL_DIALECT
          MYSQL_CHARSET: $MYSQL_CHARSET
          MYSQL_TIMEZONE: $MYSQL_TIMEZONE
      - name: run lint
        run: make lint
