name: vtm Test

on: [push]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.13
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: vtm_db
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ADMIN_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_TIMEZONE: Asia/Tokyo
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: setEnv
        run: |
          make init-env
          sed -i '/MYSQL_ROOT_USER/d' .env
          sed -i '/MYSQL_ROOT_PASSWORD/d' .env
          echo "MYSQL_ROOT_USER=root" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ADMIN_PASSWORD }}" >> .env
      - name: setup
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1
          make deps
      - name: run test
        run: go test -race -v ./...
      - name: run lint
        run: make lint
